#pragma once
// Generated by prepare_gate_road_surface.py; original PracticeStreet instance indices.
namespace BattleGateRoadCleanup {
inline const int Indices[] = {59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,407,408,409,410,411,412,413};
}
