#pragma once
// Generated by prepare_zombie_shoe_bounds.py from dominant shoe vertices.
namespace BattleZombieShoes {
struct FBounds { FVector Centre,Extent; };
inline const FBounds Bounds[2][2] = {
 { {FVector(1.3381857,-1.995295,10.5278015),FVector(5.7583337,4.3020839,11.9354283)}, {FVector(-1.3381858,-1.995295,10.5278014),FVector(5.7583341,4.3020839,11.9354283)} },
 { {FVector(1.3381322,-3.2251242,9.9285156),FVector(5.7583337,5.91214,12.5296043)}, {FVector(-1.3381324,-3.2251242,9.9285157),FVector(5.7583341,5.91214,12.5296042)} },
};
}
