#pragma once
// Generated by Scripts/prepare_battle_exit.py from sourced connector geometry.
namespace BattleRouteAnchors {
constexpr double ParkExitX=12573.162627130901;
constexpr double ParkExitY=10729.213973088190;
}
