#pragma once
// Original game dialogue. Spoken recordings remain a separate audio deliverable.
namespace BattleZombieLines { inline const TCHAR* Lines[] = {
 TEXT("You got a charger?"),
 TEXT("Is this the BeltLine or the Beltway?"),
 TEXT("I used to live in Buckhead."),
 TEXT("Braves lost again."),
 TEXT("The MARTA is coming."),
 TEXT("Brains... but make it vegan."),
 TEXT("This used to be a Kroger."),
 TEXT("I am not even from here."),
 TEXT("Ponce is a state of mind."),
 TEXT("I need to be at Chick-fil-A."),
 TEXT("My rent went up after I died."),
 TEXT("Can I borrow your hotspot?"),
 TEXT("This lane is for shambling."),
 TEXT("I only eat locally sourced brains."),
 TEXT("The tunnel has excellent acoustics."),
 TEXT("My other coffin is a scooter."),
 TEXT("I thought this was a walking meeting."),
 TEXT("Who moved the Waffle House?"),
 TEXT("Five more minutes, then cardio."),
 TEXT("I have been ghosted for centuries."),
 TEXT("That hill was not in the listing."),
 TEXT("I am training for the Peachtree."),
 TEXT("Do these shoes count as vintage?"),
 TEXT("The pollen brought me back."),
 TEXT("Put me down for plus one brain."),
 TEXT("My parking validation expired."),
 TEXT("You cannot spell undead without a nap."),
 TEXT("Meet me by the suspicious mural."),
 TEXT("I took the scenic route from the grave."),
 TEXT("Is there a student discount on brains?"),
}; }
