"""Readable fictional-game street signs at the mapped junction, review world only."""
import unreal,pathlib,math
root=pathlib.Path(unreal.Paths.project_dir());ea=unreal.get_editor_subsystem(unreal.EditorActorSubsystem);dest='/Game/BattleForTheA/Environment/PrideIntersection';cube=unreal.load_asset('/Engine/BasicShapes/Cube');dark=unreal.load_asset('/Game/BattleForTheA/Furniture/M_BenchFrame');mat=unreal.load_asset(dest+'/M_StreetSign')
if not mat:
 mat=unreal.AssetToolsHelpers.get_asset_tools().create_asset('M_StreetSign',dest,unreal.Material,unreal.MaterialFactoryNew());lib=unreal.MaterialEditingLibrary;n=lib.create_material_expression(mat,unreal.MaterialExpressionConstant3Vector);n.set_editor_property('constant',unreal.LinearColor(.012,.16,.065));lib.connect_material_property(n,'',unreal.MaterialProperty.MP_BASE_COLOR);lib.recompile_material(mat);unreal.EditorAssetLibrary.save_loaded_asset(mat)
x,y=-23800,12100;hit=unreal.PiedmontWorldTools.trace_world_surface(unreal.Vector(x,y,1600),unreal.Vector(x,y,-1200));assert hit;ground=hit[0].z
for label,pos,scale,yaw,material in [('Street sign pole',[x,y,ground+185],[.09,.09,3.7],0,dark),('10th street board',[x,y,ground+340],[.1,3.1,.52],0,mat),('Piedmont avenue board',[x,y,ground+400],[.1,3.5,.52],90,mat)]:
 a=ea.spawn_actor_from_class(unreal.StaticMeshActor,unreal.Vector(*pos));a.set_actor_label(label);a.static_mesh_component.set_static_mesh(cube);a.static_mesh_component.set_material(0,material);a.static_mesh_component.set_collision_profile_name('NoCollision');a.set_actor_scale3d(unreal.Vector(*scale));a.set_actor_rotation(unreal.Rotator(yaw=yaw),False);a.tags=[unreal.Name('PrideStreetSign')];a.set_folder_path('Midtown/PrideIntersection')
for text,yaw,z in [('10TH ST NE',0,340),('PIEDMONT AVE',90,400)]:
 for side in [0,180]:
  a=math.radians(yaw+side);actor=ea.spawn_actor_from_class(unreal.TextRenderActor,unreal.Vector(x+7*math.cos(a),y+7*math.sin(a),ground+z));actor.set_actor_rotation(unreal.Rotator(yaw=yaw+side),False);t=actor.get_component_by_class(unreal.TextRenderComponent);t.set_text(text);t.set_world_size(26);t.set_horizontal_alignment(unreal.HorizTextAligment.EHTA_CENTER);t.set_vertical_alignment(unreal.VerticalTextAligment.EVRTA_TEXT_CENTER);t.set_text_render_color(unreal.Color(255,255,245,255));t.set_text_material(unreal.load_asset('/Engine/EngineMaterials/UnlitText'));t.set_collision_enabled(unreal.CollisionEnabled.NO_COLLISION);actor.tags=[unreal.Name('PrideStreetSign')];actor.set_folder_path('Midtown/PrideIntersection')
