"""Generate the runtime park polygon from the retained OSM/terrain reference."""
import json,pathlib
from pyproj import Transformer
root=pathlib.Path(__file__).resolve().parents[1]
meta=json.loads((root/'SourceAssets/Terrain/terrain-georeference.json').read_text())
way=json.loads((root/'References/piedmont-boundary-osm.json').read_text())['elements'][0]
tr=Transformer.from_crs('EPSG:4326',meta['crs'],always_xy=True)
points=[]
for g in way['geometry'][:-1]:
 x,y=tr.transform(g['lon'],g['lat']);points.append([(x-meta['origin_utm'][0])*100/3,-(y-meta['origin_utm'][1])*100/3])
assert way['geometry'][0]==way['geometry'][-1]
header='''// Generated by Scripts/generate_park_region.py. OSM way 208357832.
// World ESU centimetres, matching the terrain's 1:3 geographic scale.
#pragma once
#include "CoreMinimal.h"
namespace BattleParkRegion {
inline const FVector2D Outline[]={
'''+''.join(f' FVector2D({x:.6f},{y:.6f}),\n' for x,y in points)+'''};
inline bool Contains(const FVector& Position,float Margin=35.f){
 const FVector2D P(Position.X,Position.Y);bool Inside=false;
 for(int I=0,J=UE_ARRAY_COUNT(Outline)-1;I<UE_ARRAY_COUNT(Outline);J=I++){
  const FVector2D A=Outline[J],B=Outline[I],D=B-A;
  const float T=FMath::Clamp(FVector2D::DotProduct(P-A,D)/FMath::Max(D.SizeSquared(),1.0),0.0,1.0);
  if(FVector2D::DistSquared(P,A+D*T)<=FMath::Square(Margin))return false;
  if((A.Y>P.Y)!=(B.Y>P.Y)&&P.X<(B.X-A.X)*(P.Y-A.Y)/(B.Y-A.Y)+A.X)Inside=!Inside;
 }return Inside;
}
inline bool ContainsSegment(const FVector& A,const FVector& B){
 const int Steps=FMath::Max(1,FMath::CeilToInt(FVector::Dist2D(A,B)/20.f));
 for(int I=0;I<=Steps;I++)if(!Contains(FMath::Lerp(A,B,float(I)/Steps)))return false;
 return true;
}
}
'''
(root/'Source/AuraPlayground/BattleParkRegion.h').write_text(header)
(root/'SourceAssets/Terrain/park-region.json').write_text(json.dumps({'source':'OSM way 208357832','frame':'Unreal ESU cm; terrain geographic scale 1:3','capsule_margin_cm':35,'outline':points},indent=2)+'\n')
