"""Use the installed connector's sourced Eastside endpoint as the first return waypoint."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
network=json.loads((root/'SourceAssets/Terrain/beltline-connector-network.json').read_text())
point=network['paths'][-1]['points_cm'][-1]
assert network['paths'][-1]['nodes'][-1]==2396740017
data={'source_node':2396740017,'source_way':1396654821,'next_trail_way':741964053,
 'description':'Northern Eastside Trail endpoint at Monroe; first return waypoint, not home finish',
 'xyz_cm':point,'georeference':'terrain-georeference.json',
 'limitation':'Full Eastside Trail, tunnel and Cabbagetown route remain unfinished.',
 'author':'2026-09-11 [codex-maclaptop]'}
(root/'SourceAssets/Terrain/battle-park-exit.json').write_text(json.dumps(data,indent=2)+'\n')
(root/'Source/AuraPlayground/BattleRouteAnchors.h').write_text('#pragma once\n// Generated by Scripts/prepare_battle_exit.py from sourced connector geometry.\nnamespace BattleRouteAnchors {\nconstexpr double ParkExitX=%.12f;\nconstexpr double ParkExitY=%.12f;\n}\n'%(point[0],point[1]))
print(data)
