"""Map-sourced street at the Murder K (Ponce Kroger) plaza.

Elliott, on build 128: "the kroger area need ALOT of work its not good ... there
is a lot of traffic there - there is an oval that leads up to it - you need to
check maps". Read that as: the plaza has no street and no traffic at all, and
the streets that really exist around the store are missing.

The store placement is already right: the OSM Kroger building centre lands
within 5 m of the game's Murder K actor, and the BeltLine Eastside Trail passes
through the actor itself. What is missing is the road. In OSM, North Avenue
Northeast runs behind the store and crosses the BeltLine about 12 m east of the
plaza, and Ponce de Leon Avenue Northeast crosses the trail 73 m west of it.
This emits the North Avenue centreline and two lane offsets for the runtime
street and its traffic.

World conversion is the retained one: EPSG:32616 through
SourceAssets/Terrain/terrain-georeference.json, 3 cm per retained unit, source Y
reflected into the Unreal east/south/up frame.
"""
import json,math
import numpy as np
from pathlib import Path
from pyproj import Transformer

root=Path(__file__).resolve().parents[1]
meta=json.loads((root/'SourceAssets/Terrain/terrain-georeference.json').read_text())
osm=json.loads((root/'References/eastside-krog-corridor-osm.json').read_text())
t=Transformer.from_crs(4326,32616,always_xy=True)
ox,oy=meta['origin_utm']
anchor=json.loads((root/'SourceAssets/Terrain/battle-checkpoints.json').read_text())['checkpoints'][0]
AX,AY=anchor['world_xyz_cm'][0],anchor['world_xyz_cm'][1]

def world(lon,lat):
 x,y=t.transform(lon,lat);return ((x-ox)/.03,-(y-oy)/.03)

segments=[]
for e in osm['elements']:
 tags=e.get('tags',{}) or {};g=e.get('geometry') or []
 if not g or tags.get('name')!='North Avenue Northeast':continue
 pts=[world(q['lon'],q['lat']) for q in g]
 if min(math.hypot(p[0]-AX,p[1]-AY) for p in pts)>22000:continue
 segments.append(pts)
assert segments,'North Avenue geometry not found'

# The extract carries only the part of each way inside its bounding box, so the
# ways do not share endpoints and cannot simply be stitched. Order the retained
# points along the street's own principal axis instead, then resample at 300 cm;
# the interpolation across the few missing mid-block pieces is straight, which
# is what a five-lane avenue is over that distance anyway.
points=np.array([p for s in segments for p in s])
centred=points-points.mean(axis=0)
axis=np.linalg.svd(centred,full_matrices=False)[2][0]
order=np.argsort(centred@axis)
points=points[order]
keep=[points[0]]
for p in points[1:]:
 if np.hypot(*(p-keep[-1]))>200 or np.hypot(*(p-keep[0]))>200:keep.append(p)
chain=np.array(keep)
route=[]
for i in range(len(chain)-1):
 a,b=chain[i],chain[i+1];d=float(np.hypot(*(b-a)));steps=max(1,int(d//300))
 for k in range(steps):route.append((a[0]+(b[0]-a[0])*k/steps,a[1]+(b[1]-a[1])*k/steps))
route.append((chain[-1][0],chain[-1][1]))
# Keep a long enough run for traffic to pass the plaza at speed: roughly 260 m
# of street, centred on the plaza. The street is cut into a north and a south
# half so the two lanes can run opposite ways.
best=min(range(len(route)),key=lambda i:math.hypot(route[i][0]-AX,route[i][1]-AY))
half=440
route=route[max(0,best-half):best+half+1]
assert len(route)>100,len(route)

def offset_route(points,lateral):
 out=[]
 for i,(x,y) in enumerate(points):
  a=points[max(0,i-1)];b=points[min(len(points)-1,i+1)]
  dx,dy=b[0]-a[0],b[1]-a[1];n=math.hypot(dx,dy) or 1
  nx,ny=-dy/n,dx/n
  out.append((x+nx*lateral,y+ny*lateral))
 return out

h=['#pragma once','// Generated by Scripts/prepare_murder_k_traffic.py from retained OSM North Avenue geometry.','namespace BattleMurderKTraffic {']
def emit(name,pts):
 h.append(f'inline const FVector {name}[] = {{')
 h.append(''.join(f'FVector({x:.2f},{y:.2f},0),' for x,y in pts))
 h.append('};')
 h.append(f'inline constexpr int32 {name}Count={len(pts)};')
emit('Centreline',route)
emit('LaneNorth',offset_route(route,300))
emit('LaneSouth',offset_route(route,-300))
h.append('}')
(root/'Source/AuraPlayground/BattleMurderKTraffic.h').write_text('\n'.join(h)+'\n')
print('centreline points',len(route))
