"""Select legacy street cubes fully covered by the installed new pavement."""
from pathlib import Path
import json,math,hashlib,re
from shapely.geometry import Polygon
from shapely.ops import unary_union
root=Path(__file__).resolve().parents[1];file=root/'SourceAssets/Terrain/PrideIntersection/PiedmontRoad.obj';verts=[];faces=[]
for line in file.read_text().splitlines():
 p=line.split()
 if p and p[0]=='v':verts.append((float(p[1]),-float(p[2])))
 elif p and p[0]=='f':faces.append(Polygon([verts[int(v.split('/')[0])-1] for v in p[1:]]))
coverage=unary_union(faces)
b=json.loads((root/'SourceAssets/Terrain/Tutorial/block.json').read_text())
# Instance indices are meaningful only while the compiled arrays match this source.
for filename, name, key in [('BattleTutorialData.h', 'Road', 'road'),
                            ('BattleTutorialBlock.h', 'Alternate', 'alternate'),
                            ('BattleTutorialBlock.h', 'StubEnds', 'stubs')]:
 source=(root/'Source/AuraPlayground'/filename).read_text().split(' '+name+'[] = {',1)[1].split('};',1)[0]
 actual=[list(map(float, row.split(','))) for row in re.findall(r'FVector\(([^)]+)\)', source)]
 expected=b[key] if key!='stubs' else [point for segment in b[key] for point in segment]
 assert len(actual)==len(expected), name
 assert all(abs(x-y)<.00001 for p,q in zip(actual,expected) for x,y in zip(p,q)), name
segments=list(zip(b['road'],b['road'][1:]))+list(zip(b['alternate'],b['alternate'][1:]))+b['stubs'];selected=[]
for i,(a,c) in enumerate(segments):
 dx,dy,dz=[c[k]-a[k] for k in range(3)];h=math.hypot(dx,dy);length=math.sqrt(h*h+dz*dz);u=(dx/h,dy/h);v=(-u[1],u[0]);half=(length+3)/2*h/length+12*abs(dz)/length;center=[(a[k]+c[k])/2 for k in range(2)];poly=Polygon([(center[0]+u[0]*s+v[0]*t,center[1]+u[1]*s+v[1]*t) for s,t in [(-half,-225),(half,-225),(half,225),(-half,225)]])
 if coverage.covers(poly.buffer(2)):
  selected.append({'instance':i,'center_xy':center,'footprint_xy':list(poly.exterior.coords),'coverage_margin_cm':2})
assert selected
header='#pragma once\n// Generated by prepare_pride_legacy_road_cleanup.py. Remove only with the mapped replacement installed.\nnamespace BattlePrideRoadCleanup {\ninline const int Indices[] = {'+','.join(str(r['instance']) for r in selected)+'};\ninline constexpr int OriginalCount='+str(len(segments))+';\n}\n';(root/'Source/AuraPlayground/BattlePrideRoadCleanup.h').write_text(header)
report={'source_sha256':hashlib.sha256(file.read_bytes()).hexdigest(),'total_legacy_instances':len(segments),'covered_instances':selected,'selected_count':len(selected),'scope':'Only fully covered projected cube footprints including pitch/body thickness; 2cm interior margin. Runtime and visual checks pending.'};(root/'Tests/Results/2026-09-13-pride-legacy-coverage.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k!='covered_instances'}))
