"""Original small flower arrangement and sourced trail approach; no personal story text."""
from pathlib import Path
import math,json,numpy as np
from shapely.geometry import LineString,Point
root=Path(__file__).resolve().parents[1];out=root/'SourceAssets/Spirit';out.mkdir(exist_ok=True)
ns={'__file__':str(root/'Scripts/prepare_cabbagetown.py')};exec((root/'Scripts/prepare_cabbagetown.py').read_text().split('krog=json.loads')[0],ns);height=ns['height']
network=json.loads((root/'SourceAssets/Terrain/eastside-trail-network.json').read_text());points=[]
for path in network['paths']:
 for x,y,z in path['points_cm']:
  p=[x,-y,z]
  if not points or math.dist(p,points[-1])>1:points.append(p)
a=np.array(points);line=LineString(a[:,:2]);station=np.r_[0,np.cumsum(np.linalg.norm(np.diff(a[:,:2],axis=0),axis=1))]
checkpoint=json.loads((root/'SourceAssets/Terrain/battle-checkpoints.json').read_text())['checkpoints'][0]['world_xyz_cm'];end=line.project(Point(checkpoint[:2]))
def at(s):return [float(np.interp(s,station,a[:,i])) for i in range(3)]
ride=[at(s) for s in np.linspace(end-3200,end-100,63)]
chase=[at(s) for s in np.linspace(end-1700,end-250,30)]
p=np.array(at(end-2200));d=np.array(at(end-2150))-p;d[2]=0;d/=np.linalg.norm(d);right=np.array([-d[1],d[0],0]);memorial=p+right*260;memorial[2]=height(*memorial[:2])-1
route={'source':'Retained OSM Eastside trail centerline and Murder K checkpoint; retained USGS elevation','policy':'Fictional small flower arrangement beside trail 66 real metres before checkpoint; not a surveyed site','memorial':memorial.tolist(),'memorial_yaw':float(math.degrees(math.atan2(d[1],d[0]))),'approach':at(end-2500),'ride':ride,'chase':[[x,y,z+70] for x,y,z in chase],'distance_before_checkpoint_cm':2200,'memorial_centerline_clearance_cm':line.distance(Point(memorial[:2]))}
assert route['memorial_centerline_clearance_cm']>240
(out/'route.json').write_text(json.dumps(route,indent=2)+'\n')
h=['#pragma once','// Generated by prepare_spirit_scene.py from retained route/terrain.','namespace BattleSpiritData {']
for name,key in [('Memorial','memorial'),('Approach','approach')]:h+=['inline const FVector '+name+'('+','.join(f'{v:.6f}' for v in route[key])+');']
h+=['inline constexpr float MemorialYaw='+str(route['memorial_yaw'])+'f;']
for name,key in [('Ride','ride'),('Chase','chase')]:h+=['inline const FVector '+name+'[] = {']+['FVector('+','.join(f'{v:.6f}' for v in p)+'),' for p in route[key]]+['};']
h+=['}'];(root/'Source/AuraPlayground/BattleSpiritData.h').write_text('\n'.join(h)+'\n')
meshes={k:([],[]) for k in ['Stems','Petals','Lavender','Centers','Stone','Ribbon']}
def patch(group,fn,nu,nv):
 v,f=meshes[group];base=len(v)
 for i in range(nu+1):
  for j in range(nv+1):v.append(fn(i/nu,j/nv))
 for i in range(nu):
  for j in range(nv):
   k=base+i*(nv+1)+j;f.extend([(k,k+nv+1,k+nv+2),(k,k+nv+2,k+1)])
def ellipsoid(group,c,size,nu=12,nv=20):
 patch(group,lambda u,v:np.array(c)+np.array(size)*[math.sin(math.pi*u)*math.cos(2*math.pi*v),math.sin(math.pi*u)*math.sin(2*math.pi*v),math.cos(math.pi*u)],nu,nv)
def stem(a,b,r):
 a,b=np.array(a),np.array(b);d=b-a;d/=np.linalg.norm(d);e=np.cross(d,[0,0,1]);e/=np.linalg.norm(e);f=np.cross(d,e)
 patch('Stems',lambda u,v:a*(1-u)+b*u+(e*math.cos(v*2*math.pi)+f*math.sin(v*2*math.pi))*r,8,8)
# Irregular shallow stone, only a quiet base beneath the bouquet.
patch('Stone',lambda u,v:np.array([38*math.sin(math.pi*u)*math.cos(v*2*math.pi),28*math.sin(math.pi*u)*math.sin(v*2*math.pi),3+3.3*math.cos(math.pi*u)])*(1+.035*math.sin(v*18*math.pi)*math.sin(u*7)),16,40)
for n in range(13):
 angle=n*2.39996;r=4+math.sqrt(n)*4.3
 head=np.array([10+math.cos(angle)*r,math.sin(angle)*r,8+(n%4)*1.2]);tail=np.array([-22+(n%3),-5+n*.8,4]);stem(tail,head,.24)
 # Narrow pointed leaves rising gently from the laid stems.
 for side in [-1,1]:
  base=tail*.4+head*.6;direction=(head-tail);direction/=np.linalg.norm(direction);cross=np.array([-direction[1],direction[0],0])
  patch('Stems',lambda u,v,base=base,cross=cross,direction=direction,side=side:base+direction*u*6+cross*(side*u*8+(v-.5)*4*math.sin(math.pi*u))+np.array([0,0,2*math.sin(math.pi*u)]),8,4)
 for j in range(11):
  theta=j*2*math.pi/11+n*.23;rad=np.array([math.cos(theta),math.sin(theta),0]);wide=np.array([-rad[1],rad[0],0])
  patch('Lavender' if n%4==0 else 'Petals',lambda u,v,head=head,rad=rad,wide=wide:head+rad*(.9+u*4.4)+wide*((v-.5)*2.2*math.sin(math.pi*u)**.55)+np.array([0,0,.65*math.sin(math.pi*u)-.6*u+.3*(2*v-1)**2]),9,6)
 ellipsoid('Centers',head+[0,0,.15],[1.35,1.35,.6],8,16)
 # Small pollen dimples catch highlights instead of a plain disc.
 for j in range(9):
  t=j*2.4;rr=.3+.18*math.sqrt(j);ellipsoid('Centers',head+[rr*math.cos(t),rr*math.sin(t),.68],[.18,.18,.15],4,6)
# A muted cloth tie around the stems; no lettering.
patch('Ribbon',lambda u,v:np.array([-11+u*3,-2.2+3.6*math.cos(v*2*math.pi),5+2*math.sin(v*2*math.pi)]),3,24)
for side in [-1,1]:patch('Ribbon',lambda u,v,side=side:np.array([-10+u*8,side*(2+u*7)+(v-.5)*2.7,4.4+1.3*math.sin(u*math.pi)]),12,3)
manifest={'author':'2026-09-11 [codex-maclaptop]','license':'Original project geometry','parts':{},'route':route['policy']}
for name,(verts,faces) in meshes.items():
 lines=['# Original small flower arrangement; OBJ Y reflected for Unreal import.']+['v %.6f %.6f %.6f'%(p[0],-p[1],p[2]) for p in verts]+['f '+' '.join(str(i+1) for i in reversed(f)) for f in faces]
 (out/(name+'.obj')).write_text('\n'.join(lines)+'\n');manifest['parts'][name]={'vertices':len(verts),'triangles':len(faces)}
(out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');print(json.dumps({'memorial':route['memorial'],'clearance':route['memorial_centerline_clearance_cm'],'parts':manifest['parts']}))
