"""Replace the overlapping gate approach cubes with one terrain-fitted surface."""
from pathlib import Path
import json,math,hashlib,re
import numpy as np
from shapely.geometry import Polygon,box
from shapely.ops import unary_union
from shapely import constrained_delaunay_triangles
root=Path(__file__).resolve().parents[1]
out=root/'SourceAssets/Terrain/GateRoad';out.mkdir(parents=True,exist_ok=True)
b=json.loads((root/'SourceAssets/Terrain/Tutorial/block.json').read_text())
# Protect generated instance indices from stale or differently ordered source data.
for filename,name,key in [('BattleTutorialData.h','Road','road'),('BattleTutorialBlock.h','Alternate','alternate'),('BattleTutorialBlock.h','StubEnds','stubs')]:
 text=(root/'Source/AuraPlayground'/filename).read_text().split(' '+name+'[] = {',1)[1].split('};',1)[0]
 actual=[list(map(float,row.split(','))) for row in re.findall(r'FVector\(([^)]+)\)',text)]
 expected=b[key] if key!='stubs' else [point for segment in b[key] for point in segment]
 assert len(actual)==len(expected) and all(abs(x-y)<.00001 for p,q in zip(actual,expected) for x,y in zip(p,q)),name
segments=list(zip(b['road'],b['road'][1:]))+list(zip(b['alternate'],b['alternate'][1:]))+b['stubs']
selected=[];polys=[]
for index,(a,c) in enumerate(segments):
 dx,dy,dz=[c[k]-a[k] for k in range(3)];h=math.hypot(dx,dy);length=math.sqrt(h*h+dz*dz)
 u=(dx/h,dy/h);v=(-u[1],u[0]);half=(length+3)/2*h/length+12*abs(dz)/length
 center=[(a[k]+c[k])/2 for k in range(2)]
 if center[0]<-18600 or center[1]>-3800:continue
 p=Polygon([(center[0]+u[0]*s+v[0]*t,center[1]+u[1]*s+v[1]*t) for s,t in [(-half,-225),(half,-225),(half,225),(-half,225)]])
 selected.append(index);polys.append(p)
assert selected
poly=unary_union(polys).buffer(3,join_style=2)
m=json.loads((root/'SourceAssets/Terrain/terrain-georeference.json').read_text())
sx,sy,sz=m['unreal_scale'];lx,ly,_=m['unreal_location_cm'];nx,ny=m['size']
source=root/'SourceAssets/Terrain/LakePathGrading/atlanta-height-lake-paths-candidate.r16'
z=(np.fromfile(source,dtype='<u2').reshape(ny,nx).astype(float)-32768)*sz/128
def height(x,y):
 gx=(x-lx)/sx;gy=(-y-ly)/sy;i,j=int(gx),int(gy);u,v=gx-i,gy-j
 a,b,c,d=z[j,i],z[j,i+1],z[j+1,i],z[j+1,i+1]
 return float(a+(b-a)*u+(d-b)*v if u>=v else a+(d-c)*u+(c-a)*v)
faces=[];x0,y0,x1,y1=poly.bounds
for j in range(int((-y1-ly)/sy),math.ceil((-y0-ly)/sy)):
 for i in range(int((x0-lx)/sx),math.ceil((x1-lx)/sx)):
  a=(lx+i*sx,-(ly+j*sy));b=(a[0]+sx,a[1]);c=(a[0],a[1]-sy);d=(b[0],c[1])
  for tri in [Polygon([a,b,d]),Polygon([a,d,c])]:
   if not poly.intersects(tri):continue
   for t in constrained_delaunay_triangles(poly.intersection(tri)).geoms:
    if t.area>.001:faces.append([[x,y,height(x,y)+12] for x,y in list(t.exterior.coords)[:3]])
coverage=unary_union([Polygon([v[:2] for v in f]) for f in faces])
assert poly.difference(coverage.buffer(.001)).area<1
verts=[v for f in faces for v in f]
lines=['o GateRoad']+[f'v {x:.5f} {-y:.5f} {h:.5f}' for x,y,h in verts]+[f'vt {x/200:.5f} {y/200:.5f}' for x,y,h in verts]
for x,y,h in verts:
 dx=(height(x+sx,y)-height(x-sx,y))/(2*sx);dy=(height(x,y+sy)-height(x,y-sy))/(2*sy);n=math.sqrt(1+dx*dx+dy*dy)
 lines.append(f'vn {-dx/n:.8f} {dy/n:.8f} {1/n:.8f}')
for k in range(0,len(verts),3):
 a,b,c=verts[k:k+3];cross=(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);order=(k,k+1,k+2) if cross<0 else (k+2,k+1,k)
 lines.append('f '+' '.join(f'{i+1}/{i+1}/{i+1}' for i in order))
(out/'GateRoad.obj').write_text('\n'.join(lines)+'\n')
report={'indices':selected,'triangles':len(faces),'bounds':list(poly.bounds),'terrain_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'terrain_changed':False,'lift_cm':12,'status':'Candidate; native collision and visual review pending'}
(out/'surface.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))

(root/'Source/AuraPlayground/BattleGateRoadCleanup.h').write_text('#pragma once\n// Generated by prepare_gate_road_surface.py; original PracticeStreet instance indices.\nnamespace BattleGateRoadCleanup {\ninline const int Indices[] = {'+','.join(map(str,selected))+'};\n}\n')
