"""Export local shoe bounds from source mesh vertices for runtime collision."""
import unreal,json,pathlib
root=pathlib.Path(unreal.Paths.project_dir());rows=json.loads(unreal.PiedmontWorldTools.inspect_zombie_shoe_bounds());assert len(rows)==4
out=['#pragma once','// Generated by prepare_zombie_shoe_bounds.py from dominant shoe vertices.','namespace BattleZombieShoes {','struct FBounds { FVector Centre,Extent; };','inline const FBounds Bounds[2][2] = {']
for style in ['Farmer','Punk']:
 selected=[next(r for r in rows if r['style']==style and r['foot']==foot) for foot in ['Foot_L','Foot_R']]
 out.append(' { '+', '.join('{FVector('+','.join(map(str,r['centre']))+'),FVector('+','.join(map(str,r['extent']))+')}' for r in selected)+' },')
out+=['};','}'];(root/'Source/AuraPlayground/BattleZombieShoeBounds.h').write_text('\n'.join(out)+'\n');(root/'work/zombie-shoe-bounds.json').write_text(json.dumps(rows,indent=2)+'\n')
