"""Native editor-game verification of the extended practice street and gate routes."""
import json,re,subprocess,pathlib,argparse
p=argparse.ArgumentParser();p.add_argument('--fps',type=int,choices=[30,60,120]);p.add_argument('--app',type=pathlib.Path);p.add_argument('--report');p.add_argument('--closure',action='store_true');p.add_argument('route',choices=['market','direct','alternate']);args=p.parse_args();root=pathlib.Path(__file__).resolve().parents[1];log=root/f'work/tutorial-route-{args.route}.log'
prefix=[str(args.app)] if args.app else ['/Volumes/Adam Assets/Unreal/UE_5.8/Engine/Binaries/Mac/UnrealEditor-Cmd',str(root/'AuraPlayground.uproject')]
if args.app:assert args.app.is_file()
if args.report:assert pathlib.Path(args.report).name==args.report
with log.open('w') as out:
 run=subprocess.run([*prefix,'/Game/PiedmontRide/Maps/PiedmontWorld?Difficulty=Easy?AutoStart=1','-game','-nullrhi','-unattended','-nosound','-BattleTutorialAudit',*([f'-ExecCmds=t.MaxFPS {args.fps}'] if args.fps else []),*(['-BattleMarketClosureReview'] if args.closure else []),*(['-BattleTutorialMarket'] if args.route=='market' else ['-BattleTutorialAlternate'] if args.route=='alternate' else []),'-stdout'],stdout=out,stderr=subprocess.STDOUT,timeout=240)
rows=re.findall(r'BattleTutorialAudit: (\{[^\n]+\})',log.read_text());r=json.loads(rows[-1]) if rows else {'passed':False,'reason':'Missing audit'};r.update(fps_cap_requested=args.fps,exit_code=run.returncode,route=args.route,log=str(log),scope='Keyboard-controlled native route fixture; scenery, market closure and freeform bypass checks unaccepted.');r['market_fence_sweeps']='MarketClosureAudit: 237 fence crossing sweeps passed' in log.read_text();r['closure_removed_after_start']='MarketClosureAudit: removed after gateway start' in log.read_text();r['passed']=r['passed'] and (not args.closure or args.route=='market' or r['closure_removed_after_start']) and run.returncode==0 and (not args.closure or r['market_fence_sweeps'])
(root/'Tests/Results'/(args.report or f"2026-09-12-market-{'closure' if args.closure else 'extension'}-{args.route}.json")).write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r));raise SystemExit(0 if r['passed'] else 1)
